# Generated by Django 5.1 on 2024-08-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="live_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
