# Generated by Django 5.1 on 2024-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_certificate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["priority"]},
        ),
        migrations.AddField(
            model_name="skill",
            name="priority",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
