# Generated by Django 5.1 on 2024-08-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_skill_options_skill_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobexperience",
            name="end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="jobexperience",
            name="start_date",
            field=models.DateField(),
        ),
    ]
