# Generated by Django 5.1 on 2024-08-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_jobexperience_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobexperience",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.DateField(),
        ),
    ]
